[package]
name = "eth-proxy"
version = "0.1.0"
edition = "2018"

[dependencies]
log = "^0.4"
log4rs = "^1"

serde = { version = "^1", features = ["derive"] }
serde_json = "^1"

actix-web = { version = "^3", features=["rustls"] }